ci:
  autofix_commit_msg: |
    [pre-commit] fixes from hooks
  autofix_prs: true
  autoupdate_branch: "main"
  autoupdate_commit_msg: "chore: pre-commit.ci autoupdate"
  autoupdate_schedule: monthly
  skip: []
  submodules: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]
      - id: check-merge-conflict

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        args: [--write-changes]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.29.0
    hooks:
      - id: zizmor
