name: docs

on:
  push:
  pull_request:

defaults:
  run:
      shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@main
        with:
          environment-file: env.yml
          cache-downloads: true
          environment-name: dissectBCL
      - name: build docs
        run: |
          micromamba activate dissectBCL
          pip install .[docs]
          cd docs
          make html