name: docs

on:
  push:
  pull_request:

defaults:
  run:
      shell: bash -l {0}

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge,bioconda
          channel-priority: true
          environment-file: env.yml
          environment-name: dissectBCL
          activate-environment: dissectBCL
          conda-remove-defaults: true
      - name: build docs
        run: |
          pip install .[docs]
          cd docs
          make html