# pytests

name: pytest

on:
  push:
  pull_request:

permissions:
  contents: read

defaults:
  run:
      shell: bash -l {0}

jobs:
  run_pytests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: conda-incubator/setup-miniconda@be893c923ea9cf1cf7cd510fbdde27c7e18cbdcb # v4.1.0
        with:
          channels: conda-forge,bioconda
          channel-priority: true
          environment-file: env.yml
          cache-downloads: true
          activate-environment: dissectBCL
          conda-remove-defaults: true
      - name: pip
        run: |
          pip install .[dev]
      - name: pytest
        run: |
          pytest