# pytests

name: pytest

on:
  push:
  pull_request:

defaults:
  run:
      shell: bash -l {0}

jobs:
  run_pytests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge,bioconda
          channel-priority: true
          environment-file: env.yml
          cache-downloads: true
          activate-environment: dissectBCL
          conda-remove-defaults: true
      - name: pip
        run: |
          pip install .[dev]
      - name: pytest
        run: |
          pytest