# pytests

name: pytest

on:
  push:
  pull_request:

defaults:
  run:
      shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@main
        with:
          environment-file: env.yml
          cache-downloads: true
          environment-name: dissectBCL
      - name: build
        run: |
          micromamba activate dissectBCL
          pip install .[dev]
      - name: pytest
        run: |
          micromamba activate dissectBCL
          coverage run -m pytest
          coverage report -m
